name: Build VcXsrv

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  x64:
    uses: ./.github/workflows/build-architecture.yml
    with:
      build_arch: x64
      msvc_arch: amd64
      archive_prefix: vcxsrv-64

  arm64:
    needs: x64
    uses: ./.github/workflows/build-architecture.yml
    with:
      build_arch: arm64
      msvc_arch: amd64_arm64
      archive_prefix: vcxsrv-arm64
